title: "Курс по языку программирования Python"
description: "Основы Python для начинающих. Простое и понятное объяснение всех ключевых конструкций от переменных до функций"
language: "python"
docker_image: "basics_python:latest"
