title:
  ru: "Ruby"
description:
  ru: "Обучение Ruby для тех кто уже умеет программировать и хочет изучить этот язык без длинных вступлений. Текстовые уроки и тренажер в браузере"
learning_description:
  ru: "Разберётесь в базовом синтаксисе Ruby — это фундаментальный навык, который позволит вам писать чистый и лаконичный код. После курса вы сможете работать с классами, модулями, коллекциями, функциями и блоками, а также использовать встроенные возможности языка для удобной обработки данных"
use_cases_description:
  ru: "Ruby – это удобный и лаконичный язык программирования, широко используемый в веб-разработке (Ruby on Rails), автоматизации и тестировании. Он прост в освоении, имеет чистый синтаксис и ускоряет разработку стартапов и бизнес-приложений. Ruby востребован в крупных IT-компаниях и стартапах"
docker_image: "basics_ruby:latest"
