title: "Курс по языку программирования Ruby"
description: "Обучение Ruby для тех кто уже умеет программировать и хочет изучить этот язык без длинных вступлений. Текстовые уроки и тренажер в браузере"
language: "ruby"
docker_image: "basics_ruby:latest"
